version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
#  app:
#    container_name: app
#    restart: always
#    build: .  # 빌드할 Dockerfile 위치 경로
#    ports:
#      - "3001:3001"
