name: Node.js DEPLOY

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SETUP NODE.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        run: npm ci

      - name: RUN TEST
        run: npm test
