name: Node.js DEPLOY

on:
  push:
    branches: master

jobs:
  CI_CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SETUP NODE.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: INSTALL package.json
        run: npm ci

      - name: RUN TEST
        run: npm test

      - name: SETUP .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_CLIENT_URI: "https://localhost:3000"
          envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
          envkey_MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          envkey_MONGO_USER: ${{ secrets.MONGO_USER }}
          envkey_MONGO_PWD: ${{ secrets.MONGO_PWD }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          envkey_FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
          envkey_FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
          envkey_KAKAO_APP_ID: ${{ secrets.KAKAO_APP_ID }}
          envkey_KAKAO_APP_SECRET: ${{ secrets.KAKAO_APP_SECRET }}
          file_name: .env

      - name: RUN BUILD
        run: npm run build

      - name: SETUP QEMU
        uses: docker/setup-qemu-action@v1

      - name: SETUP Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: LOGIN to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: DOCKER BUILD and PUSH
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: begin0dev/blog-server:latest
